- name: Declare variable at play level
  hosts: all
  connection: local
  vars:
    URL: play.example.com
  tasks:
    - name: Access a variable
      ansible.builtin.debug:
        msg: URL == {{URL}}


- name: Declare variable at task level
  hosts: all
  connection: local
  tasks:
    - name: Declare and Access a variable
      ansible.builtin.debug:
        msg: URL == {{URL}}
        vars:
          URL: task.example.com

