- name: Print Hello
  ansible.builtin.debug:
    msg: Hello from role

- name: Print HELLO
  ansible.builtin.debug:
    msg: URL == {{URL}}


- name: Print HELLO
  ansible.builtin.debug:
  msg: URL == {{URL1}}